"use client";

import { FormEvent, useEffect, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { createClient } from "@/lib/supabase/client";
import styles from "./resume-sites.module.css";

type Site = { id: string; title: string; theme_key: string; generation_status: string; updated_at: string; resume_site_publications: { slug: string; is_active: boolean; published_at: string } | { slug: string; is_active: boolean; published_at: string }[] | null };

export default function ResumeSitesPage() {
  const [supabase] = useState(() => createClient()); const [user, setUser] = useState<User | null>(null); const [sites, setSites] = useState<Site[]>([]); const [loading, setLoading] = useState(true); const [email, setEmail] = useState(""); const [message, setMessage] = useState("");
  async function load() { setLoading(true); const response = await fetch("/api/resume-sites"); const payload = await response.json(); setSites(payload.sites || []); setLoading(false); }
  useEffect(() => { void supabase.auth.getSession().then(({ data }) => { setUser(data.session?.user || null); if (data.session?.user) void load(); else setLoading(false); }); const { data } = supabase.auth.onAuthStateChange((_event, session) => { setUser(session?.user || null); if (session?.user) void load(); else setSites([]); }); return () => data.subscription.unsubscribe(); }, [supabase]);
  async function signIn(event: FormEvent) { event.preventDefault(); const callback = new URL("/auth/callback", window.location.origin); callback.searchParams.set("next", "/resume-sites"); const { error } = await supabase.auth.signInWithOtp({ email, options: { emailRedirectTo: callback.toString() } }); setMessage(error ? error.message : "登录链接已发送，请前往邮箱完成登录。"); }
  return <main className={styles.shell}><header className={styles.topbar}><a href="/" className={styles.brand}>AI <span>超级求职助手</span></a><nav className={styles.navlinks}><a href="/">岗位匹配</a><a className={styles.primaryLink} href="/resume-sites/new">创建在线简历</a></nav></header><div className={styles.content}><section className={styles.intro}><div><p className={styles.eyebrow}>MY RESUME SITES</p><h1>管理你的求职主页。</h1></div><p>草稿保持私密，只有你主动发布的快照才可以被外部访问。</p></section>{!user ? <section className={styles.panel}><h2>登录后查看草稿和公开链接</h2><form className={styles.authBox} onSubmit={signIn}><input type="email" required value={email} onChange={(event) => setEmail(event.target.value)} placeholder="邮箱地址"/><button>发送登录链接</button></form>{message && <p className={styles.notice}>{message}</p>}</section> : loading ? <div className={styles.loading}>正在加载在线简历…</div> : sites.length === 0 ? <div className={styles.empty}><h2>还没有在线简历</h2><p>上传一份 PDF，几分钟内生成你的第一个求职主页。</p><a className={styles.primaryLink} href="/resume-sites/new">立即创建 →</a></div> : <div className={styles.siteGrid}>{sites.map((site) => { const raw = site.resume_site_publications; const publication = Array.isArray(raw) ? raw[0] : raw; return <article className={styles.siteCard} key={site.id}><span className={styles.status}>{publication?.is_active ? "已发布" : "私有草稿"}</span><h2>{site.title}</h2><p>{site.theme_key} · 更新于 {new Date(site.updated_at).toLocaleString("zh-CN", { hour12: false })}</p><div className={styles.cardActions}><a href={`/resume-sites/${site.id}/edit`}>继续编辑</a>{publication?.is_active && <a href={`/r/${publication.slug}`} target="_blank">查看公开页 ↗</a>}</div></article>; })}</div>}</div></main>;
}
