"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useParams } from "next/navigation";
import { ResumeRenderer } from "@/components/resume-sites/ResumeRenderer";
import { emptyContent, normalizeContent, normalizeSlug, sectionKeys, type ResumeSiteContent, type SectionKey, type ThemeKey } from "@/lib/resume-sites/schema";
import styles from "./editor.module.css";

type Site = { id: string; title: string; theme_key: ThemeKey; draft_content: ResumeSiteContent; revision: number; resume_site_publications: { slug: string; is_active: boolean } | { slug: string; is_active: boolean }[] | null };
const themes: Array<{ id: ThemeKey; name: string; desc: string }> = [{ id: "clean-professional", name: "清爽专业", desc: "克制、清晰" }, { id: "product-launch", name: "产品主页风", desc: "价值与成果" }, { id: "creative-portfolio", name: "创意作品集", desc: "编辑式叙事" }, { id: "enterprise-tech", name: "企业科技风", desc: "深色技术感" }];
const sectionLabels: Record<SectionKey, string> = { strengths: "核心优势", experiences: "职业经历", projects: "代表项目", education: "教育背景", skills: "技能图谱" };
const uid = (prefix: string) => `${prefix}-${crypto.randomUUID().slice(0, 8)}`;

export default function ResumeSiteEditorPage() {
  const { id } = useParams<{ id: string }>();
  const [site, setSite] = useState<Site | null>(null); const [content, setContent] = useState<ResumeSiteContent>(emptyContent); const [theme, setTheme] = useState<ThemeKey>("clean-professional"); const [title, setTitle] = useState(""); const [revision, setRevision] = useState(1);
  const [dirty, setDirty] = useState(false); const [saveState, setSaveState] = useState("正在加载…"); const [error, setError] = useState(""); const [previewMobile, setPreviewMobile] = useState(false); const [mobileTab, setMobileTab] = useState<"edit" | "preview">("edit");
  const [publishOpen, setPublishOpen] = useState(false); const [slug, setSlug] = useState(""); const [confirmed, setConfirmed] = useState(false); const [publishing, setPublishing] = useState(false); const changeVersion = useRef(0); const saving = useRef(false);

  useEffect(() => { void fetch(`/api/resume-sites/${id}`).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error); const loaded = payload.site as Site; const publication = Array.isArray(loaded.resume_site_publications) ? loaded.resume_site_publications[0] : loaded.resume_site_publications; setSite(loaded); setContent(normalizeContent(loaded.draft_content)); setTheme(loaded.theme_key); setTitle(loaded.title); setRevision(loaded.revision); setSlug(publication?.slug || normalizeSlug((loaded.draft_content as ResumeSiteContent).basics?.fullName || "") || `career-${loaded.id.slice(0, 6)}`); setSaveState("已保存"); }).catch((caught) => { setError(caught instanceof Error ? caught.message : "草稿加载失败。"); setSaveState("加载失败"); }); }, [id]);

  const saveDraft = useCallback(async () => {
    if (!site || saving.current) return false;
    saving.current = true; const version = changeVersion.current; setSaveState("保存中…");
    try {
      const response = await fetch(`/api/resume-sites/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, themeKey: theme, content, revision }) });
      const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "保存失败。");
      setRevision(payload.revision); if (changeVersion.current === version) { setDirty(false); setSaveState("已保存"); } else setSaveState("有新修改待保存");
      return true;
    } catch (caught) { setSaveState("保存失败"); setError(caught instanceof Error ? caught.message : "保存失败。"); return false; }
    finally { saving.current = false; }
  }, [content, id, revision, site, theme, title]);

  useEffect(() => { if (!dirty || !site) return; const timer = window.setTimeout(() => void saveDraft(), 850); return () => window.clearTimeout(timer); }, [dirty, site, saveDraft]);
  function changed(next: ResumeSiteContent) { changeVersion.current += 1; setContent(next); setDirty(true); setError(""); }
  function changeTheme(next: ThemeKey) { changeVersion.current += 1; setTheme(next); setDirty(true); }
  function updateBasics(field: keyof ResumeSiteContent["basics"], value: string) { changed({ ...content, basics: { ...content.basics, [field]: value } }); }
  function moveSection(key: SectionKey, delta: number) { const order = [...content.sectionOrder]; const from = order.indexOf(key); const to = from + delta; if (to < 0 || to >= order.length) return; [order[from], order[to]] = [order[to], order[from]]; changed({ ...content, sectionOrder: order }); }
  function toggleSection(key: SectionKey) { const hidden = content.hiddenSections.includes(key) ? content.hiddenSections.filter((item) => item !== key) : [...content.hiddenSections, key]; changed({ ...content, hiddenSections: hidden }); }

  async function publish() {
    if (!confirmed) return setError("请先确认公开内容和联系方式。"); setPublishing(true); setError("");
    if (dirty && !(await saveDraft())) { setPublishing(false); return; }
    try { const response = await fetch(`/api/resume-sites/${id}/publish`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ slug }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setSlug(payload.publication.slug); setPublishOpen(false); setConfirmed(false); setSite((current) => current ? { ...current, resume_site_publications: { slug: payload.publication.slug, is_active: true } } : current); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "发布失败。"); } finally { setPublishing(false); }
  }
  async function unpublish() { if (!confirm("取消发布后，公开链接将立即不可访问。继续吗？")) return; const response = await fetch(`/api/resume-sites/${id}/unpublish`, { method: "POST" }); if (response.ok) setSite((current) => current ? { ...current, resume_site_publications: current.resume_site_publications ? { ...(Array.isArray(current.resume_site_publications) ? current.resume_site_publications[0] : current.resume_site_publications), is_active: false } : null } : current); }
  const publication = site ? (Array.isArray(site.resume_site_publications) ? site.resume_site_publications[0] : site.resume_site_publications) : null;

  if (!site) return <main className={styles.shell}><div className={styles.bar}><a href="/resume-sites">← 返回</a><h1>在线简历编辑器</h1><div/></div><div style={{ padding: 50 }}>{error || "正在加载草稿…"}</div></main>;
  return <main className={styles.shell}>
    <header className={styles.bar}><a href="/resume-sites">← 我的在线简历</a><h1>{title || "在线简历编辑器"}</h1><div className={styles.barActions}><span className={styles.saveState}>{saveState}</span><button onClick={() => setPreviewMobile((value) => !value)}>{previewMobile ? "桌面预览" : "手机预览"}</button>{publication?.is_active && <button onClick={unpublish}>取消发布</button>}<button className={styles.publishButton} onClick={() => setPublishOpen(true)}>{publication?.is_active ? "更新发布" : "发布分享"}</button></div></header>
    <div className={styles.mobileToggle}><button onClick={() => setMobileTab("edit")}>编辑</button><button onClick={() => setMobileTab("preview")}>预览</button></div>
    <div className={styles.workspace}><aside className={`${styles.editor} ${mobileTab === "preview" ? styles.hiddenMobile : ""}`}>
      {error && <p className={styles.error}>{error}</p>}
      <section className={styles.panel}><h2>页面设置</h2><label className={styles.field}><span>管理名称</span><input value={title} onChange={(event) => { changeVersion.current += 1; setTitle(event.target.value); setDirty(true); }}/></label><div className={styles.themes}>{themes.map((item) => <button key={item.id} className={`${styles.theme} ${theme === item.id ? styles.themeActive : ""}`} onClick={() => changeTheme(item.id)}><strong>{item.name}</strong><span>{item.desc}</span></button>)}</div></section>
      <section className={styles.panel}><h2>个人定位</h2><label className={styles.field}><span>姓名</span><input value={content.basics.fullName} onChange={(event) => updateBasics("fullName", event.target.value)}/></label><label className={styles.field}><span>职业定位</span><input value={content.basics.headline} onChange={(event) => updateBasics("headline", event.target.value)}/></label><label className={styles.field}><span>个人简介</span><textarea value={content.basics.summary} onChange={(event) => updateBasics("summary", event.target.value)}/></label><label className={styles.field}><span>所在地</span><input value={content.basics.location} onChange={(event) => updateBasics("location", event.target.value)}/></label></section>
      <section className={styles.panel}><h2>模块顺序与显示</h2>{content.sectionOrder.map((key) => <div className={styles.sectionRow} key={key}><label><input type="checkbox" checked={!content.hiddenSections.includes(key)} onChange={() => toggleSection(key)}/> {sectionLabels[key]}</label><div className={styles.sectionControls}><button onClick={() => moveSection(key, -1)}>↑</button><button onClick={() => moveSection(key, 1)}>↓</button></div></div>)}</section>
      <section className={styles.panel}><h2>核心优势</h2>{content.strengths.map((item, index) => <div className={styles.item} key={item.id}><label className={styles.field}><span>标题</span><input value={item.title} onChange={(event) => changed({ ...content, strengths: content.strengths.map((row, i) => i === index ? { ...row, title: event.target.value } : row) })}/></label><label className={styles.field}><span>说明</span><textarea value={item.description} onChange={(event) => changed({ ...content, strengths: content.strengths.map((row, i) => i === index ? { ...row, description: event.target.value } : row) })}/></label><div className={styles.itemActions}><button onClick={() => changed({ ...content, strengths: content.strengths.filter((_, i) => i !== index) })}>删除</button></div></div>)}<button className={styles.addButton} onClick={() => changed({ ...content, strengths: [...content.strengths, { id: uid("strength"), title: "新的优势", description: "" }] })}>＋ 添加优势</button></section>
      <section className={styles.panel}><h2>职业经历</h2>{content.experiences.map((item, index) => <div className={styles.item} key={item.id}>{(["company", "role", "period"] as const).map((field) => <label className={styles.field} key={field}><span>{{ company: "公司", role: "职位", period: "时间" }[field]}</span><input value={item[field]} onChange={(event) => changed({ ...content, experiences: content.experiences.map((row, i) => i === index ? { ...row, [field]: event.target.value } : row) })}/></label>)}<label className={styles.field}><span>经历说明</span><textarea value={item.summary} onChange={(event) => changed({ ...content, experiences: content.experiences.map((row, i) => i === index ? { ...row, summary: event.target.value } : row) })}/></label><label className={styles.field}><span>亮点（每行一条）</span><textarea value={item.highlights.join("\n")} onChange={(event) => changed({ ...content, experiences: content.experiences.map((row, i) => i === index ? { ...row, highlights: event.target.value.split("\n") } : row) })}/></label><div className={styles.itemActions}><button onClick={() => changed({ ...content, experiences: content.experiences.filter((_, i) => i !== index) })}>删除</button></div></div>)}<button className={styles.addButton} onClick={() => changed({ ...content, experiences: [...content.experiences, { id: uid("experience"), company: "", role: "新经历", period: "", summary: "", highlights: [] }] })}>＋ 添加经历</button></section>
      <section className={styles.panel}><h2>代表项目</h2>{content.projects.map((item, index) => <div className={styles.item} key={item.id}>{(["name", "role", "link"] as const).map((field) => <label className={styles.field} key={field}><span>{{ name: "项目名称", role: "项目角色", link: "项目链接" }[field]}</span><input value={item[field] || ""} onChange={(event) => changed({ ...content, projects: content.projects.map((row, i) => i === index ? { ...row, [field]: event.target.value } : row) })}/></label>)}<label className={styles.field}><span>项目说明</span><textarea value={item.description} onChange={(event) => changed({ ...content, projects: content.projects.map((row, i) => i === index ? { ...row, description: event.target.value } : row) })}/></label><label className={styles.field}><span>亮点（每行一条）</span><textarea value={item.highlights.join("\n")} onChange={(event) => changed({ ...content, projects: content.projects.map((row, i) => i === index ? { ...row, highlights: event.target.value.split("\n") } : row) })}/></label><div className={styles.itemActions}><button onClick={() => changed({ ...content, projects: content.projects.filter((_, i) => i !== index) })}>删除</button></div></div>)}<button className={styles.addButton} onClick={() => changed({ ...content, projects: [...content.projects, { id: uid("project"), name: "新项目", role: "", description: "", highlights: [] }] })}>＋ 添加项目</button></section>
      <section className={styles.panel}><h2>教育背景</h2>{content.education.map((item, index) => <div className={styles.item} key={item.id}>{(["school", "degree", "period"] as const).map((field) => <label className={styles.field} key={field}><span>{{ school: "学校", degree: "学历 / 专业", period: "时间" }[field]}</span><input value={item[field]} onChange={(event) => changed({ ...content, education: content.education.map((row, i) => i === index ? { ...row, [field]: event.target.value } : row) })}/></label>)}<div className={styles.itemActions}><button onClick={() => changed({ ...content, education: content.education.filter((_, i) => i !== index) })}>删除</button></div></div>)}<button className={styles.addButton} onClick={() => changed({ ...content, education: [...content.education, { id: uid("education"), school: "", degree: "", period: "" }] })}>＋ 添加教育背景</button></section>
      <section className={styles.panel}><h2>技能图谱</h2>{content.skillGroups.map((item, index) => <div className={styles.item} key={item.id}><label className={styles.field}><span>技能组名称</span><input value={item.name} onChange={(event) => changed({ ...content, skillGroups: content.skillGroups.map((row, i) => i === index ? { ...row, name: event.target.value } : row) })}/></label><label className={styles.field}><span>技能（用逗号分隔）</span><input value={item.skills.join("，")} onChange={(event) => changed({ ...content, skillGroups: content.skillGroups.map((row, i) => i === index ? { ...row, skills: event.target.value.split(/[，,]/) } : row) })}/></label><div className={styles.itemActions}><button onClick={() => changed({ ...content, skillGroups: content.skillGroups.filter((_, i) => i !== index) })}>删除</button></div></div>)}<button className={styles.addButton} onClick={() => changed({ ...content, skillGroups: [...content.skillGroups, { id: uid("skill"), name: "技能组", skills: [] }] })}>＋ 添加技能组</button></section>
      <section className={styles.panel}><h2>联系方式</h2>{content.contacts.map((item, index) => <div className={styles.item} key={item.id}><label className={styles.contactVisibility}><input type="checkbox" checked={item.visible} onChange={(event) => changed({ ...content, contacts: content.contacts.map((row, i) => i === index ? { ...row, visible: event.target.checked } : row) })}/> 允许在公开页显示</label>{(["label", "value", "url"] as const).map((field) => <label className={styles.field} key={field}><span>{{ label: "标签", value: "显示内容", url: "跳转链接" }[field]}</span><input value={item[field] || ""} onChange={(event) => changed({ ...content, contacts: content.contacts.map((row, i) => i === index ? { ...row, [field]: event.target.value } : row) })}/></label>)}<div className={styles.itemActions}><button onClick={() => changed({ ...content, contacts: content.contacts.filter((_, i) => i !== index) })}>删除</button></div></div>)}<button className={styles.addButton} onClick={() => changed({ ...content, contacts: [...content.contacts, { id: uid("contact"), type: "other", label: "联系方式", value: "", url: "", visible: false }] })}>＋ 添加联系方式</button></section>
      <section className={styles.panel}><h2>页面行动按钮</h2><label className={styles.field}><span>结束语</span><input value={content.cta.headline} onChange={(event) => changed({ ...content, cta: { ...content.cta, headline: event.target.value } })}/></label><label className={styles.field}><span>按钮文字</span><input value={content.cta.label} onChange={(event) => changed({ ...content, cta: { ...content.cta, label: event.target.value } })}/></label><label className={styles.field}><span>按钮链接</span><input value={content.cta.href} onChange={(event) => changed({ ...content, cta: { ...content.cta, href: event.target.value } })}/></label></section>
    </aside><section className={`${styles.previewPane} ${mobileTab === "edit" ? styles.hiddenMobile : ""}`}><div className={`${styles.previewFrame} ${previewMobile ? styles.mobileFrame : ""}`}><ResumeRenderer content={content} theme={theme} preview/></div></section></div>
    {publishOpen && <aside className={styles.publishPanel}><h2>{publication?.is_active ? "更新公开页面" : "发布在线简历"}</h2><p>只有本次发布快照会公开；未勾选的联系方式不会进入公开数据。</p><label className={styles.field}><span>公开链接</span><input type="text" value={slug} onChange={(event) => setSlug(normalizeSlug(event.target.value))}/></label><p>访问地址：/r/{slug || "your-name"}</p><label className={styles.confirm}><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)}/>我已确认姓名、经历、联系方式和外部链接可以公开访问。</label>{error && <p className={styles.error}>{error}</p>}<div className={styles.publishActions}><button onClick={() => setPublishOpen(false)}>稍后再说</button><button disabled={publishing || !confirmed} onClick={publish}>{publishing ? "发布中…" : publication?.is_active ? "更新发布" : "确认发布"}</button></div></aside>}
  </main>;
}
